### PR TITLE
feat: add vetur tags

### PR DESCRIPTION
**Pull request by andrewvasilchuk**
These changes add support for [Vetur tags](https://vuejs.github.io/vetur/component-data.html#other-frameworks).

### CODE REVIEW

**Comment by andrewvasilchuk** [comment]
@nicolasbeauvais, Hello. Please, add `hacktoberfest-accepted` label.

**Comment by andrewvasilchuk** [comment]
@nicolasbeauvais, fixing the conflict right now :)

**Comment by nicolasbeauvais** [comment]
Hello @andrewvasilchuk, your two PR were not compatible, if you can resolve the conflicts I would gladly merge your proposed modifications.

**Comment by andrewvasilchuk** [comment]
@nicolasbeauvais, The conflicts are resolved.

**Comment by nicolasbeauvais** [comment]
Thank you @andrewvasilchuk !

**Pull request merged**
