### PR TITLE
Migration to Vue 2.x

### PR DESCRIPTION
**Pull request by AWolf81**
I've migrated your component to Vue.js 2.x and tested it locally in my current project.

It is working. It would be great to have your plugin working with latest Vue version. Before these modifications I've had errors in the browser console (some breaking changes).

(I've also added some unit tests.)

### CODE REVIEW

**Comment by nicolasbeauvais** [comment]
Thanks a lot for contributing @AWolf81, 

I will gladly merge your PR and create a v1.0.0 for the package with it. Could you just make all the tests pass?

**Comment by AWolf81** [comment]
You're welcome.

I'd like to add my skipped tests later. Once I have more time again.

I have some questions to the code:
- Do you have an example that is using the attribute `data-action`? I've added a test but the use-case is not clear to me.
- Is it possible to run Travis CI with-out a PR? I'd like to check why one of my tests failed there. It was working locally but not at Travis. I think it's because `location.href` is different.

**Comment by nicolasbeauvais** [comment]
No worries for your tests :)

The `data-action` attribute is to create a share button that triggers an app on a smartphone (in our case it's used to share on Whatsapp) http://sivasankar.in/whatsapp-share-button-website/

You just need to add your fork https://github.com/AWolf81/vue-social-sharing on TravisCI, after that, all your commit will be tested even before doing a PR :)

**Comment by AWolf81** [comment]
OK, thanks for the advice with adding travis to my fork.

And good to know how the data-action is used, so I can now verify and improve that test.

**Pull request merged**
