### PR TITLE
Local events added

### PR DESCRIPTION
**Pull request by anteriovieira**
Add local events:

```html
 <social-sharing ... @open="open()" @close="close()">
   ...
 </social-sharing>
```

### CODE REVIEW

**Comment by nicolasbeauvais** [comment]
Hello @anteriovieira,

thank you for contributing to `vue-social-sharing`!

Could you tell me what would be the use case for local events? This will help me to write documentation & tests for it

**Comment by anteriovieira** [comment]
Hi @nicolasbeauvais ,

I use the sharing on some page of a teaching platform and need to trigger sensors to register the sharing event.

Example:

```html
 <social-sharing ... @open="open()" @close="close()">
   ...
 </social-sharing>
```

```js
export default {
  // ..
  methods: {
    open() {
        this.$sensor.track('Video shared', { /* properties */ })
    }
  }
}
```
Is it possible to trigger an event when shared?

**Comment by Diferno** [comment]
:+1:

**Comment by nicolasbeauvais** [comment]
Hello @anteriovieira, your PR is merged and part of the [2.2.11 release](https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v2.2.11).

As explained in #62 it is not in the scope of this package to validate the success of a share action as it would involve implementing API calls.

Sorry for the wait, and thank you again for contributing :+1:

**Pull request merged**
