### PR TITLE
Add simple compatibility with vue 3

### PR DESCRIPTION
**Pull request by CKGrafico**
In theory this is enough to have this working with vue 3
haw

### CODE REVIEW

**Comment by CKGrafico** [comment]
I hope will help in #271

**Review by brambekkers — APPROVED** [review]

**Comment by savina-09** [comment]
@nicolasbeauvais @CKGrafico 

When would these changes be available to use in Vue3 projects?

**Comment by nicolasbeauvais** [comment]
Hello @CKGrafico, thank you for your pull request, making vue-social-sharing compatible with vue3 will require more work as some current feature of the library use parts of Vue that do not exist any more. I will continue the work on the master branch and let you know when a first beta version is available.

**Comment by nicolasbeauvais** [comment]
@savina-09 When I will have implemented and tested all the current features

**Comment by nicolasbeauvais** [comment]
I released a first alpha build, tell me how it goes https://github.com/nicolasbeauvais/vue-social-sharing/releases/tag/v4.0.0-alpha1

**Comment by nicolasbeauvais** [comment]
The Vue 3 compatible build can be installed with `npm install vue-social-sharing@next`

**Comment by WillianBabuu** [comment]
thank you for the vue 3 support it works very fine. but I have problems first is instagram not supported? and I get these errors just after click a post

>  Uncaught DOMException: Permission denied to access property "__v_isRef" on cross-origin object

**Comment by ankurk91** [comment]
It has been one year, publish the stable version

**Pull request merged**
