### PR TITLE
update "vue-social-sharing.js" to last PR

### PR DESCRIPTION
**Pull request by ram-you**

### CODE REVIEW

**Comment by nicolasbeauvais** [comment]
I haven't notice that all your changes were on in the `dist/`directory. You should only modify the files in the `src` directory. Everything in `dist` is generated by `npm run build` so all your changes were erased.

I modified the src files according to your proposed changes and retagged v2.1.0.

Everything should work correctly now, thank you again for contributing :smile:

**Comment by ram-you** [comment]
I'm so sorry

**Comment by nicolasbeauvais** [comment]
No worries :smiley:

**Comment by ram-you** [comment]
on npm 2.1.0 still have old files. 
(Désolé encore une fois)

**Pull request closed without merging**
